name: ini
version: 0.0.5
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-ini
description: Read and write .ini files
dev_dependencies:
  unittest: any
